# crp_accounting/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import TrialBalanceView
# --- Import ALL necessary views ---
# Import from the specific view modules based on your structure
from .views.coa import (
    AccountGroupViewSet,
    AccountViewSet,
    AccountBalanceView,
    AccountLedgerView
)
from .views.journal import VoucherViewSet
from .views.party import PartyViewSet
from .views.period import FiscalYearViewSet, AccountingPeriodViewSet
# --- Import from the reports views ---

from .views.profit_loss import ProfitLossView # <<< IMPORT the new view

# --- Router Setup ---
router = DefaultRouter()
# ... (router registrations remain the same) ...
router.register(r'account-groups', AccountGroupViewSet, basename='accountgroup')
router.register(r'accounts', AccountViewSet, basename='account')
router.register(r'vouchers', VoucherViewSet, basename='voucher')
router.register(r'parties', PartyViewSet, basename='party')
router.register(r'fiscal-years', FiscalYearViewSet, basename='fiscal-year')
router.register(r'accounting-periods', AccountingPeriodViewSet, basename='accounting-period')


# --- App Namespace ---
app_name = 'crp_accounting_api'

# --- URL Patterns ---
urlpatterns = [
    # 1. Include all URLs generated by the router for the ViewSets
    path('', include(router.urls)),

    # 2. Add specific paths for non-ViewSet COA views (Ledger/Balance)
    path('accounts/<int:account_pk>/balance/', AccountBalanceView.as_view(), name='account-balance'),
    path('accounts/<int:account_pk>/ledger/', AccountLedgerView.as_view(), name='account-ledger'),

    # 3. Add specific paths for Report views
    path(
        'reports/trial-balance/',
        TrialBalanceView.as_view(),
        name='report-trial-balance'
    ),
    # --- ADDED URL pattern for Profit & Loss ---
    path(
        'reports/profit-loss/',          # URL path for the P&L report
        ProfitLossView.as_view(),        # The view class instance
        name='report-profit-loss'        # URL name for reversing
    ),
    # --- End ADDED URL ---

    # --- Add future report URLs here ---
    # path('reports/balance-sheet/', BalanceSheetView.as_view(), name='report-balance-sheet'),
    # path('reports/cash-flow/', CashFlowView.as_view(), name='report-cash-flow'),

]